version: '3.8'

services:
  database :
    image : mariadb
    container_name: mariadb
    env_file: .env
    volumes: 
      - ./mariadb:/var/lib/mysql
    networks: 
      - inception
    build: requirements/mariadb
    restart: always

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    env_file: .env
    volumes: 
      - ./wordpress:/var/www/wordpress
    networks: 
      - inception
    depends_on: 
      - database
    build: requirements/nginx
    ports: 
      - "8443:443"
    restart: always

  wordpress :
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes: 
      - ./wordpress:/var/www/wordpress
    networks: 
      - inception
    depends_on: 
      - database
    build: requirements/wordpress
    restart: always
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    ports:
      - "8080:80"
    networks:
      - inception
    depends_on:
      - database
    restart: always

networks:
  inception:
    name : inception
    driver : bridge