version: '3.8'

services:
  database :
    image : mariadb
    container_name: mariadb
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks: 
      - inception
    build: requirements/mariadb
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    env_file: .env
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    depends_on: 
      - database
    build: requirements/nginx
    ports: 
      - "443:443"
    restart: always

  wordpress :
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    depends_on: 
      - database
    build: requirements/wordpress
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/afadlane/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/afadlane/data/mariadb'

networks:
  inception:
    name : inception
    driver : bridge