FROM debian:11

EXPOSE 3306

RUN apt -y update && apt -y upgrade

RUN apt -y install mariadb-server

COPY conf/mariadb.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/script.sh /var/tools/setup.sh 

RUN chmod 777 /var/tools/setup.sh

CMD ["/var/tools/setup.sh"]