FROM debian:11

RUN apt-get update && apt-get install -y wget php  php-mysql

WORKDIR /var/www/html/


RUN wget https://www.adminer.org/latest.php && mv latest.php index.php

EXPOSE 8080
#  start the built-in web server 
CMD ["php", "-S", "0.0.0.0:8080"]
