FROM debian:11

RUN apt-get -y update && apt-get -y upgrade && apt -y install wget

WORKDIR /var/www/

RUN apt-get install -y php\
    php-fpm\
    php-mysql\
    mariadb-client
# FastCGI Process Manager.handle PHP-based web applications.
COPY ./script.sh /var/www/

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf


RUN  chmod 777  /var/www/script.sh

RUN wget https://wordpress.org/latest.tar.gz && \
    tar -xzvf latest.tar.gz && \
    rm -fr latest.tar.gz


COPY ./conf/wp-config.php /var/www/wordpress

EXPOSE 9000

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

RUN		chown -R root:root /var/www/wordpress

CMD ["/var/www/script.sh"]