FROM debian:11

RUN apt-get -y update && apt-get -y upgrade
WORKDIR /usr/share/nginx/html/
RUN apt install -y nginx 
RUN apt install -y curl 
RUN apt install -y openssl 

RUN mkdir -p /etc/nginx/ssl 

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout \
   /etc/nginx/ssl/private-key.key -out /etc/nginx/ssl/afadlane.42.fr.crt -subj "/"
COPY index.html .
COPY profile-image.jpg .

COPY ./nginx.conf /etc/nginx/sites-enabled/default.conf 

CMD [ "nginx", "-g", "daemon off;" ]