FROM debian:11

RUN apt -y update && apt -y upgrade
RUN apt install -y nginx 
RUN apt install -y openssl 
# delete default nginx conf
RUN rm -rf /etc/nginx/sites-enabled/default
RUN mkdir -p /etc/nginx/ssl 

#subj disable propmp of openssl cmd.

RUN openssl req -x509 -nodes \
    -keyout /etc/nginx/ssl/private-key.key \
    -out /etc/nginx/ssl/afadlane.42.fr.crt \
    -subj "/" 

COPY ./conf/nginx.conf /etc/nginx/sites-enabled/default.conf 

CMD [ "nginx", "-g", "daemon off;" ]