name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

    - name: Generate configure script if not present
      run: |
        if [ ! -f ./configure ]; then
          autoreconf -i
        fi

    - name: Make configure executable
      run: chmod +x configure

    - name: Run configure
      run: ./configure

    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

