name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

    - name: Generate configure script if configure.ac is present and configure is not
      run: |
        if [ -f ./configure.ac ] && [ ! -f ./configure ]; then
          autoreconf -i
        fi

    - name: Make configure executable if it exists
      run: |
        if [ -f ./configure ]; then
          chmod +x ./configure
        else
          echo "Error: configure script not found and could not be generated."
          exit 1
        fi

    - name: Run configure
      run: ./configure

    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
